name: Build and Push Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: luqmanshaban/jsonx:latest
          build-args: |
            PORT=${{ secrets.PORT }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}

      # Step 4: Deploy the Docker container to the VPS
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull luqmanshaban/jsonx:latest
            docker rm -f jsonx || true
            docker run -d -p 4442:4442 --name jsonx \
              -e PORT="${{ secrets.PORT }}" \
              -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
              luqmanshaban/jsonx:latest